version: "3.5"

services:
  vanilla:
    image: nexforumcontainers.azurecr.io/vanilla/container:${DOCKER_TAG}
    volumes:
      - config:/srv/vanilla-repositories/vanilla/conf
      - upload:/srv/vanilla-repositories/vanilla/uploads
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPHINX_SERVER: sphinx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "2222:2222"

  sphinx:
    image: nexforumcontainers.azurecr.io/vanilla/sphinx
    volumes:
      - ${DOLLAR}{WEBAPP_STORAGE_HOME}/sphinx:/usr/local/etc/sphinx/data/
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
